FROM adoptopenjdk/openjdk11:jdk-11.0.2.9-slim
MAINTAINER ajinkyatarnekar@gmail.com
WORKDIR /opt
ENV PORT 8081
EXPOSE 8081
COPY build/libs/newsletter-iam-1.0-SNAPSHOT.jar /opt/newsletter-iam.jar
ENTRYPOINT exec java $JAVA_OPTS -jar newsletter-iam.jar